# Generated by Django 4.1.1 on 2022-10-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='Taskship',
        ),
    ]
