# Generated by Django 4.1.1 on 2022-10-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='author',
                    to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='executor',
                    to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='status',
                    to='statuses.status')),
            ],
        ),
    ]
