# Generated by Django 4.1.1 on 2022-10-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_tasks_delete_taskship'),
        ('statuses', '0001_initial'),
        ('tasks', '0002_task_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='statuses.status'),
        ),
        migrations.CreateModel(
            name='LabelForTask',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='labels.label')),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='tasks.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(through='tasks.LabelForTask',
                                         to='labels.label'),
        ),
    ]
